# Change these first
owner: theyosh # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: TheYOSH.nl
    url: https://theyosh.nl
    maxResponseTime: 10000
  - name: TerrariumPI
    url: https://terrarium.theyosh.nl
    maxResponseTime: 10000
  - name: TerrariumPI Documentation
    url: https://theyosh.github.io/TerrariumPI/
    maxResponseTime: 10000
  - name: Matrix server
    url: https://matrix.theyosh.nl
    icon: https://matrix.org/assets/favicon.svg
    maxResponseTime: 10000
  - name: Mastodon server
    url: https://mastodon.theyosh.nl
    maxResponseTime: 10000
  - name: Cloud server
    url: https://cloud.theyosh.nl
    maxResponseTime: 10000
  - name: Weblate server
    url: https://weblate.theyosh.nl
    maxResponseTime: 10000
  - name: Imap server
    check: "tcp-ping"
    url: mail.theyosh.nl
    port: 993
    maxResponseTime: 10000
  - name: Mail1.theyosh.nl
    check: "tcp-ping"
    url: mail1.theyosh.nl
    port: 25
    maxResponseTime: 10000
  - name: Mail2.theyosh.nl
    check: "tcp-ping"
    url: mail2.theyosh.nl
    port: 25
    maxResponseTime: 10000
  - name: Mail3.theyosh.nl
    check: "tcp-ping"
    url: mail3.theyosh.nl
    port: 25
    maxResponseTime: 10000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: ./logo-512.png
  favicon: ./logo-192.png
  #faviconSvg: ./upptime-icon.svg
  name: Upptime
  introTitle: "Uptime status theyosh.nl"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/theyosh/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: ./
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
